
    // init all Enum, config
    var cms = {
        configs : {
            TopBoxHomeHighlight: 0,
            TopBoxMostView: 0,
            TopBoxAssessmentHighlight: 0,
            TopBoxMostSearch: 0,
            TopBoxNewsFocus: 0,
            CKVERSION: 0,
            SpellCheckerApiDomain: "",
            NoImage: "",
            CropSizeCMS: "",
            ngConfirm: {
                warningColor: 'orange',
                warningOKText: 'Có',
                warningOKClass: 'btn-orange',
                warningCancelText: 'Hủy',
                warningCancelClass: 'btn-gray',
                infoColor: 'blue',
                infoOKClass: 'btn-blue',
                infoCancelText: 'Hủy',
                infoCancelClass: 'btn-gray',
                dangerOKClass: 'btn-red',
            },
            UploadProject: "",
            VideoAESKey: "",
            VideoAESIV: "",
            VideoViewDomain: "",
            VideoUploadDomain: "",
            VideoUploadDomainClient: "",
            VideoUploadHandler: "",
            UploadHandler: "",
            VideoThumbDomain: "",
            ViewDomain: "",
            ProductionDomain: "",
            NewsAutoSave: {
                Enable: false,
                Interval: 0
            }
        },
        message: {
            invalid: 'Dữ liệu không hợp lệ',
            checked: 'Bạn phải check vào ô này',
            empty: 'Bạn không được để trống',
            update_succsess: 'Dữ liệu cập nhật thành công',
            delete_succsess: 'Dữ liệu đã được xóa',
            update_error: 'Cập nhật không thành công!',
            itemRetuned: 'Bài viết đã được trả lại',
            itemUnPublished: 'Bài viết đã được gỡ bỏ',
            itemDeleted: 'Bài viết đã được xóa bỏ',
            itemPublished: 'Bài viết đã được xuất bản',
            itemPending: 'Bài viết đã được gửi biên tập',
            itemRecivedEdit: 'Bài viết đã được nhận biên tập',
            itemPendingApprove: 'Bài viết đã được gửi duyệt',
            itemRecivedApprove: 'Bài viết đã được nhận duyệt',
            itemAdded: 'Bài viết đã được thêm',
            itemExisted: 'Bài viết đã tồn tại',
            itemMax: 'Danh sách đã đủ bài viết',
            NewsTypeInvalid: 'Loại tin không hợp lệ',
            DisplayTypeInvalid: 'Kiểu hiển thị không hợp lệ',
            max: 'input is too long',
            number_min: 'too low',
            number_max: 'too high',
            url: 'invalid URL',
            number: 'not a number',
            password_repeat: 'mật khẩu không đúng',
            repeat: 'không đúng',
            uncomplete: 'Dữ liệu nhập chưa hoàn thành',
            select: 'Please select an option',
            confirmWarningTitle: 'Cảnh báo!',
            confirmSave: 'Bạn có chắc muốn lưu bài này?',
            confirmDoPublish: 'Bạn có chắc muốn xuất bản bài này?',
            confirmDoPending: 'Bạn có chắc muốn gửi biên tập bài này?',
            confirmDoRecivedEdit: 'Bạn có chắc muốn nhận biên tập bài này?',
            confirmDoPendingApprove: 'Bạn có chắc muốn gửi duyệt bài này?',
            confirmDoRecivedApprove: 'Bạn có chắc muốn nhận duyệt bài này?',
            confirmDoUnPublish: 'Bạn có chắc muốn gỡ bài này?',
            confirmDoReturn: 'Bạn có chắc muốn trả lại bài này?',
            confirmDoDelete: 'Bạn có chắc muốn xóa bài này?',
            confirmActiveBoxNewsEmbed: 'Bạn có chắc muốn mở box tin?',
            confirmDeactiveBoxNewsEmbed: 'Bạn có chắc muốn ẩn box tin?',
            confirmDeleteBoxNewsEmbed: 'Bạn có chắc muốn xóa box tin này?'
        }
    }