//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVG.WIS.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVG.WIS.Local.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishment of Thanhthanhdat company.
        /// </summary>
        public static string About2002 {
            get {
                return ResourceManager.GetString("About2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quynh Thien processing exported wood factory introduction.
        /// </summary>
        public static string About2005 {
            get {
                return ResourceManager.GetString("About2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pho Hai processing exported wood factory introduction.
        /// </summary>
        public static string About2007 {
            get {
                return ResourceManager.GetString("About2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishment of Quang Phu woodchip processing factory for export.
        /// </summary>
        public static string About2008 {
            get {
                return ResourceManager.GetString("About2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Plantation Factory, invest in 2.500 ha forest in Quynh Chau, Nghe An.
        /// </summary>
        public static string About2010 {
            get {
                return ResourceManager.GetString("About2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export and Consumer Wood Processing Factory in Ky Anh, Ha Tinh province and Cam Thuy, Thanh Hoa.
        /// </summary>
        public static string About2012 {
            get {
                return ResourceManager.GetString("About2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Exported Wood Processing Factory Nghi Son 2 introduction.
        /// </summary>
        public static string About2013 {
            get {
                return ResourceManager.GetString("About2013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Establishment of Thanh Thanh Dat Vu Quang MDF Joint Stock Company.
        /// </summary>
        public static string About2016 {
            get {
                return ResourceManager.GetString("About2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishment of Quang Tri Forest Products Co., Ltd. and Okal Quang Binh Wood Joint Stock Company.
        /// </summary>
        public static string About2017 {
            get {
                return ResourceManager.GetString("About2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invested in Xuan Linh industrial cluster, Nghi Xuan district.
        /// </summary>
        public static string About2018 {
            get {
                return ResourceManager.GetString("About2018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishment of Thanh Thanh Dat mechanical and glue factory.
        /// </summary>
        public static string About2019 {
            get {
                return ResourceManager.GetString("About2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/about-us.
        /// </summary>
        public static string AboutUsAlias {
            get {
                return ResourceManager.GetString("AboutUsAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDF Thanh Thanh Dat Joint Stock Company born in 2016 is a member unit of Thanh Thanh Dat Corporation. With the courage to be different, the strong creativity and sophistication in the view and action, MDF Thanh Thanh Dat JSC pioneered to open new, practical values ​​and unique ideas to create our own brand. At the same time, with the top goal being towards green industry, friendly wood production and environmental protection, MDF Thanh Thanh Dat JSC is committed to creating products that meet the needs of c [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutUsContent {
            get {
                return ResourceManager.GetString("AboutUsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh Thanh Dat MDF company - Our vision is becoming the top leading unit in wood panel industry in Vietnam.
        /// </summary>
        public static string AboutUsDesc {
            get {
                return ResourceManager.GetString("AboutUsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With so many experienced years in MDF HDF production field and the continuously innovative technology, MDF ThanhThanhDat JSC guarantee to bring the best product and customized solution to ourr customer. This will help us to have a sustainable future together..
        /// </summary>
        public static string AboutUsHome {
            get {
                return ResourceManager.GetString("AboutUsHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDF THADACO JSC.
        /// </summary>
        public static string AboutUsText {
            get {
                return ResourceManager.GetString("AboutUsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About | MDF THADACO JSC.
        /// </summary>
        public static string AboutUsTitle {
            get {
                return ResourceManager.GetString("AboutUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address*.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blogs.
        /// </summary>
        public static string Blogs {
            get {
                return ResourceManager.GetString("Blogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/news/blogs.
        /// </summary>
        public static string BlogsAlias {
            get {
                return ResourceManager.GetString("BlogsAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blogs desc.
        /// </summary>
        public static string BlogsDesc {
            get {
                return ResourceManager.GetString("BlogsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blogs | Thanhthanhdat Panel Limited Comany.
        /// </summary>
        public static string BlogsTitle {
            get {
                return ResourceManager.GetString("BlogsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career.
        /// </summary>
        public static string Career {
            get {
                return ResourceManager.GetString("Career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/career.
        /// </summary>
        public static string CareerAlias {
            get {
                return ResourceManager.GetString("CareerAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs at ThanhThanhDat MDF + Finds job at ThanhThanhDat MDF factory company.
        /// </summary>
        public static string CareerDesc {
            get {
                return ResourceManager.GetString("CareerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career | MDF THADACO JSC.
        /// </summary>
        public static string CareerTitle {
            get {
                return ResourceManager.GetString("CareerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification.
        /// </summary>
        public static string Certification {
            get {
                return ResourceManager.GetString("Certification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Address: Vu Quang District Industrial Cluster, Tho Dien, Vu Quang District, Ha Tinh Province..
        /// </summary>
        public static string CompanyAddress {
            get {
                return ResourceManager.GetString("CompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THANH THANH DAT COMPANY LIMITED.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDF THADACO JSC.
        /// </summary>
        public static string CompanyNameDetail {
            get {
                return ResourceManager.GetString("CompanyNameDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company News.
        /// </summary>
        public static string CompanyNews {
            get {
                return ResourceManager.GetString("CompanyNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/news/company-news.
        /// </summary>
        public static string CompanyNewsAlias {
            get {
                return ResourceManager.GetString("CompanyNewsAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company news desc.
        /// </summary>
        public static string CompanyNewsDesc {
            get {
                return ResourceManager.GetString("CompanyNewsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company News | Thanhthanhdat Panel Limited Comany.
        /// </summary>
        public static string CompanyNewsTitle {
            get {
                return ResourceManager.GetString("CompanyNewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/contact.
        /// </summary>
        public static string ContactAlias {
            get {
                return ResourceManager.GetString("ContactAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnam - Vinh city. ThanhThanhDat Company. 34 Nguyen Si Sach Road, Vinh city. Tel: 02383536373; Email: ....
        /// </summary>
        public static string ContactDesc {
            get {
                return ResourceManager.GetString("ContactDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact information.
        /// </summary>
        public static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string ContactInfomation {
            get {
                return ResourceManager.GetString("ContactInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi liên hệ thành công.
        /// </summary>
        public static string ContactSucess {
            get {
                return ResourceManager.GetString("ContactSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact | MDF Thadaco JSC.
        /// </summary>
        public static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development History.
        /// </summary>
        public static string DevelopmentHistory {
            get {
                return ResourceManager.GetString("DevelopmentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email*.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular News.
        /// </summary>
        public static string FeaturedNews {
            get {
                return ResourceManager.GetString("FeaturedNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Products.
        /// </summary>
        public static string FeaturedProduct {
            get {
                return ResourceManager.GetString("FeaturedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founder&apos;s Note.
        /// </summary>
        public static string FoundersNote {
            get {
                return ResourceManager.GetString("FoundersNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our company&apos;s vision is to become the leading enterprise in Vietnam in the field of forest product processing, with the main product produced from plantation timber as the key, creating a sustainable development. Besides constantly striving to create high quality products and services to meet the needs of society. MDF Thanh Thanh Dat JSC also focuses on caring and developing human resources both physically and mentally to encourage employees to create new values ​​for the Company in particular and the socie [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FoundersNoteContent {
            get {
                return ResourceManager.GetString("FoundersNoteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullname*.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General information.
        /// </summary>
        public static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en.
        /// </summary>
        public static string HomeAlias {
            get {
                return ResourceManager.GetString("HomeAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh Thanh Dat is a company specialized in manufacturing industrial MDF with modern production lines and years of experience in the market.
        /// </summary>
        public static string HomeDesc {
            get {
                return ResourceManager.GetString("HomeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDF Thanh Thanh Dat Wood Joint Stock Company - MDF THADACO JSC.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email to subscribe to receive the latest information from Thanhthanhdat.
        /// </summary>
        public static string InputEmailForSubcribe {
            get {
                return ResourceManager.GetString("InputEmailForSubcribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join now.
        /// </summary>
        public static string JoinNow {
            get {
                return ResourceManager.GetString("JoinNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join with us.
        /// </summary>
        public static string JoinUs {
            get {
                return ResourceManager.GetString("JoinUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At MDF ThanhThanhDat JSC wood panel company, all employee will be nourished and encouraged to develop by fair and transparent still competitve perfomance review process..
        /// </summary>
        public static string JoinUsTitle {
            get {
                return ResourceManager.GetString("JoinUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/news.
        /// </summary>
        public static string NewsAlias {
            get {
                return ResourceManager.GetString("NewsAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest news ThanhThanhDat Company Updating.
        /// </summary>
        public static string NewsDesc {
            get {
                return ResourceManager.GetString("NewsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///News | MDF Thadaco JSC.
        /// </summary>
        public static string NewsTitle {
            get {
                return ResourceManager.GetString("NewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Address: ThanhThanhDat Building, No 34, Nguyen Sy Sach Street, Vinh City, Nghe An.
        /// </summary>
        public static string OfficeAddress {
            get {
                return ResourceManager.GetString("OfficeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founder&apos;s note.
        /// </summary>
        public static string OurLeaders {
            get {
                return ResourceManager.GetString("OurLeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The goal of Thanh Thanh Dat MDF Joint Stock Company is to become a leading enterprise in industrial wood production, contributing more to the development of the community and the country. &lt;/br&gt;
        ///We always operate according to the principle: Creativity, the will to create new values &lt;/br&gt;
        ///Chairman: Mr. Tran Quang Luan.
        /// </summary>
        public static string OurLeadersContent {
            get {
                return ResourceManager.GetString("OurLeadersContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our partner.
        /// </summary>
        public static string OurPartner {
            get {
                return ResourceManager.GetString("OurPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Products.
        /// </summary>
        public static string OurProducts {
            get {
                return ResourceManager.GetString("OurProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our main product including industrial wood panel MDF and HDF. Being produced with modern production line, our product will meet all your requirment and serve different uses in daily life..
        /// </summary>
        public static string OurProductsTitle {
            get {
                return ResourceManager.GetString("OurProductsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone*.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/product.
        /// </summary>
        public static string ProductAlias {
            get {
                return ResourceManager.GetString("ProductAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium density fiberboard (MDF) is a highly useful wood-based panel with good machinability. MDF has a consistent structure and density and a very smooth ....
        /// </summary>
        public static string ProductDesc {
            get {
                return ResourceManager.GetString("ProductDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh Thanh Dat Medium density fiberboard (MDF) is a highly useful wood-based panel with good machinability. MDF has a consistent structure and density and a very smooth ....
        /// </summary>
        public static string ProductDetailMeta {
            get {
                return ResourceManager.GetString("ProductDetailMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products | MDF THADACO JSC.
        /// </summary>
        public static string ProductTitle {
            get {
                return ResourceManager.GetString("ProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruitment.
        /// </summary>
        public static string Recruitment {
            get {
                return ResourceManager.GetString("Recruitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tech specification doc.
        /// </summary>
        public static string TechSpecification {
            get {
                return ResourceManager.GetString("TechSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VACANCIES.
        /// </summary>
        public static string VACANCIES {
            get {
                return ResourceManager.GetString("VACANCIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View less.
        /// </summary>
        public static string ViewLess {
            get {
                return ResourceManager.GetString("ViewLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View more.
        /// </summary>
        public static string ViewMore {
            get {
                return ResourceManager.GetString("ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industrial Wood MDF.
        /// </summary>
        public static string WoodMDF {
            get {
                return ResourceManager.GetString("WoodMDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufactured on modern lines imported from Italy, industrial wooden of Thanh Thanh Dat ensure standards of smoothly and durability suitable for all purposes of use..
        /// </summary>
        public static string WoodMDFContent {
            get {
                return ResourceManager.GetString("WoodMDFContent", resourceCulture);
            }
        }
    }
}
